### ISSUE TITLE
Broken live collaboration

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw-room#114] opened 2020-10-21 23:49 UTC
## Play by Play

Today at 7:12 AM (9 hours ago) https://github.com/excalidraw/excalidraw-room/pull/109 was merged which fixed the build which triggered a new release to be deployed and broke live collaboration.

![image](https://user-images.githubusercontent.com/197597/96801591-caac4900-13bc-11eb-8425-72648cff80f5.png)

I tried reverting it but the previous commit actually didn't build. I tried to reverting another pull request ( https://github.com/excalidraw/excalidraw-room/pull/112 ) but that didn't build either.

Instead of blindly reverting things, I looked at the commit that last built from heroku (August 21) and reverted the code to that commit ( https://github.com/excalidraw/excalidraw-room/pull/113 )

This brought the old version alive and live collaboration is now working again.

## Next steps

Right now we should be good with that old version, the problem is mitigated. Some thoughts about what to do next:

* We should figure out how to restore the changes that were done since then.
* We should add a test that makes sure that the build actually works somehow.
* We should have some alarms so we are notified by automation rather than confused customer.

**Comment by ahasanen** [comment] 2020-10-21 23:55
Thanks for the quick fix! 🙏

**Comment by vjeux** [comment] 2020-10-21 23:55
Looks like alerting would push the price from the current $7 a month to $25 a month.

![image](https://user-images.githubusercontent.com/197597/96802221-40fd7b00-13be-11eb-9513-b6d7d1d50938.png)

**Comment by asvinours** [comment] 2020-10-22 01:00
first, I'm terribly sorry for breaking the app today.

I tried to reproduce the issue locally by running the frontend and the backend on different domains, and I can't reproduce it.
I'm running the HEAD of the backend repository, and all WebSocket requests sent to the backend come back with an access-control-allow-origin header with the value being the domain of the frontend app.
The value of the access-control-allow-origin header on the response is matching the origin header of the request.

I'm down to help fix it but I need to figure out a way to reproduce it first.

**Comment by vjeux** [comment] 2020-10-22 05:15
@asvinours no worries, I don't think it was your fault. We shouldn't be able to make the entire server crash by fixing something.

I am not familiar with how to run it or the app itself, @lipis, @idlewinn and @floydophone built it I believe. It would be nice if they could help you out debugging this.

**Comment by vjeux** [comment] 2020-10-22 05:17
Numbers are back looking healthy

![image](https://user-images.githubusercontent.com/197597/96827763-2392d600-13eb-11eb-8e42-a5e1427cac17.png)

**Comment by dwelle** [comment] 2020-10-22 08:42
Oh, my fault for not properly testing before merging. Thing is, I'm running the exact same thing on a different server so I assumed it's safe to merge.

**Comment by asvinours** [comment] 2020-10-22 12:21
https://github.com/socketio/socket.io-client/issues/1140#issuecomment-661255887
https://github.com/socketio/socket.io-client/issues/1140#issuecomment-697018223

I think the second comment is pointing out the issue.

**Comment by dwelle** [comment] 2020-10-22 12:29
I think the types are simply wrong. The `2.x.x` and `3.x.x` have the server as `thisArg` instead of an argument, and in `4.x.x` the `handlePreflightRequest()` API is removed altogether.

**Comment by kbariotis** [comment] 2020-10-22 13:54
> We should add a test that makes sure that the build actually works somehow.

At the moment, Heroku itself picks up a new commit was merged and starts the deployment process. We can alter that to make a GitHub action do the deploy so we are able to run a test before that that will actually test the server is working before doing the deployment. We also have a staging app on Heroku that we can use to make an integration test but don't quote me on that, it may need a bit more investigation.

There is an issue already #13 that I'm suspecting it was meant to allow doing that but never picked up.

**Comment by lipis** [comment] 2020-12-23 19:42
Should be ok now.. no?

**Closed by lipis** 2020-12-23 19:42 UTC
